### ISSUE TITLE
Make view transitions smoother and remove the jumpiness exposed by iOS 9

### ISSUE THREAD

**Issue by brendandm** [ChesapeakeCommons/stream-mapper-ios#1]
Whereas uneven view transitions were less obvious in previous versions of iOS, 9 has brought some problems to the surface. Changes to view content are out of sync with transition times, so to start we should investigate ways to produce are more static view stack given that only a few are really dynamic.

**Comment by razwasserstein** [comment]
Hey  I have transitions problems in my app on ios9 (I used jquery mobile for traditions), what should I do?
On safari IOS 9 it works fine...

**Comment by brendandm** [comment]
@razwasserstein We're not as familiar with jQuery Mobile but the latest Angular release contains a patch that seems to fix this problem (at least for location changes). Not sure if the WebKit team plans to fix the UIWebView bug but depending on your situation that may not be the root cause.

**Comment by brendandm** [comment]
Upgrading to Angular 1.4.6 solved the underlying problem. Minor presentation-layer issues related to view transitions should be addressed in future Stream Mapper releases.
